### ISSUE TITLE
Requires equational-reasoning at runtime

### ISSUE THREAD

**Issue by ttuegel** [konn/ghc-typelits-presburger#2]
The GHC plugin requires `equational-reasoning` to be installed when the plugin is used, but this doesn't appear to be documented. My issue was solved by adding `build-inputs: equational-reasoning` to my package.

**Comment by konn** [comment]
Thank you for your report and sorry for late reply.
I'm planning to entirely reconstruct this package to make compatible with GHC-7.2, and I will fix this issue within it.

**Comment by konn** [comment]
This has been fixed by #12. Sorry for late response.
