### ISSUE TITLE
Cannot build due to missing dependency

### ISSUE THREAD

**Issue by crockeea** [konn/ghc-typelits-presburger#5]
ghc-typelits-presburger depends on generic-unification, which isn't on Hackage. As a result, I can't build this repo.

**Comment by konn** [comment]
Oops, I unintendedly uploaded an unnecessarily newer version. I will fix that. Sorry for the inconvenience. I will release the fixed version within this week.

**Comment by konn** [comment]
Now fixed on Hackage (without deps for generic-unification).
